# Generated by Django 4.0.4 on 2022-04-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ra', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModalidadeHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=100)),
                ('horas_limite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorasAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_atribuidas', models.IntegerField()),
                ('modalidade_horas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agylapi.modalidadehoras')),
                ('ra_aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agylapi.aluno')),
            ],
        ),
    ]
